mysql:
  host: 127.0.0.1
  port: 3306
  db: gogo_blog
  user: root
  password: 123456
  log_level: dev


system:
  host: 127.0.0.1
  port: 8090
  env: dev
  mode: release

logger:
  level: info
  prefix: '[gogo]'
  director: log
  show_line: true
  log_in_console: true

uploads:
  size: 2
  path: uploads
